### ISSUE TITLE
Where to put links from the class? 

### ISSUE THREAD

**Issue by jackiekazil** [18F/hackathontrainingday#36]
@leahbannon, I have links that I said I would post after the class for stuff we looked at during the class. Where is a good place to do this?

**Comment by leahbannon** [comment]
Add a section to the homepage?

**Comment by jackiekazil** [comment]
@leahbannon -- this homepage http://18f.github.io/hackathontrainingday/  (just want to be clear)

**Comment by leahbannon** [comment]
yes
